default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dir_str_development
  username: rubyuser
  password: newlife

  host: localhost

  port: 5432

test:
  <<: *default
  database: dir_str_test
  username: rubyuser
  password: newlife

  host: localhost

  port: 5432
